### ISSUE TITLE
Publish docker image to registry

### ISSUE THREAD

**Issue by kjetilhartveit** [TimoWilhelm/local-neon-http-proxy#2]
Hi Timo, first of all great initiative and work (although I haven't actually tested it yet!).

Just wondering if it was possible to publish the docker image for the http proxy somewhere so that they can be consumed less verbosely?

Inspired by what Matt has done for PlanetScale: https://github.com/mattrobenolt/ps-http-sim

In my docker-compose.yml with PlanetScale I was able to use the following brief config to start the proxy:

```yml
version: "3.8"
name: some-project
services:
    planetscale_proxy_local:
        image: ghcr.io/mattrobenolt/ps-http-sim:latest
        command:
            [
                "-listen-port=8080",
                "-mysql-dbname=some-db",
                "-mysql-addr=host.docker.internal",
                "-mysql-max-rows=10000",
            ]
        ports:
            - "8080:8080"
```

If you're wondering yes I need to get off PlanetScale due to their announcement of removing the hobby tier :)
